# Generated by Django 4.0.6 on 2022-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(unique=True)),
                ('text', models.TextField()),
                ('user_id', models.BigIntegerField()),
                ('user_screen_name', models.CharField(max_length=200)),
                ('user_description', models.CharField(max_length=250, null=True)),
                ('tweet_type', models.CharField(max_length=100, null=True)),
                ('reply_to_tweet_id', models.BigIntegerField(null=True)),
                ('retweet_to_tweet_id', models.BigIntegerField(null=True)),
                ('reply_to_user_id', models.BigIntegerField(null=True)),
                ('retweet_to_user_id', models.BigIntegerField(null=True)),
                ('hashtags', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('hashtag_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'hashtags',
                'unique_together': {('tweet_id', 'user_id', 'hashtag_name')},
            },
        ),
    ]
